/*********************************************************************
 * Name:          main.h
 * Purpose:       Declares simple wxWidgets application with GUI
 *                 created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:       wxWidgets license (www.wxwidgets.org)
 *
 * Notes:        Note that all GUI creation code is declared in
 *                 gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
public:
    virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase
{
private:
    bool m_gameRunning;
    bool m_waitForSpace;
    int m_paddleMaxSpeed;
    int m_paddleHeight;
    int m_ballMovement[2];
    int m_score[2]; // 0 - player, 1 - AI
    wxLog* m_log;
    
public:
    MainFrame(wxWindow* parent, bool showLog);
    virtual ~MainFrame();

protected:
    // protected event handlers
    virtual void OnCloseFrame(wxCloseEvent& event);
    virtual void OnExitClick(wxCommandEvent& event);
    virtual void OnNewGameClick(wxCommandEvent& event);
    virtual void OnTimerTick(wxTimerEvent& event);
    void HnadleOnKeyDown(wxKeyEvent& event);

private:
    void StartRound();
    void InitRound();
    void StopGame();
    void PlayerScores();
    void AiScores();
    void ClearScore();
    bool CheckForWinner();

    void MovePaddleTowardCoordinate(wxPanel* paddle,
            int desiredYcoordinate, const wxSize& gameboardSize);
    wxPoint MoveBall();
    bool HitsPaddle(wxPanel* paddle, int yCoord);
};

#endif //__main__
