/*********************************************************************
 * Name:          main.cpp
 * Purpose:       Implements simple wxWidgets application with GUI
 *                created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:       wxWidgets license (www.wxwidgets.org)
 *
 * Notes:         Note that all GUI creation code is implemented in
 *                gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"
#include "util.h"
#include <cmath>

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
    SetTopWindow(new MainFrame(NULL));
    GetTopWindow()->Show();

    // true = enter the main loop
    return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow* parent)
    : MainFrameBase(parent)
{
    m_paddleHeight = this->_padMine->GetSize().GetHeight();
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
    Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
    Destroy();
}
void MainFrame::OnNewGameClick(wxCommandEvent& event)
{
    this->m_gameTimer.Start(10);
}

void MainFrame::OnTimerTick(wxTimerEvent& event)
{
    wxPoint bgPosition = this->_pongBackground->GetScreenPosition();
    wxSize bgSize = this->_pongBackground->GetSize();
    
    const wxPoint pt = getMousePositionInsideArea(bgPosition, bgSize);
    
    wxPoint padPosition = this->_padMine->GetPosition();
    padPosition.y = std::min(pt.y, bgSize.GetHeight() - m_paddleHeight);

    this->_padMine->SetPosition(padPosition);
}

void MainFrame::MoveUserPaddle(const wxPoint& mousePosition)
{
    
}
