/*********************************************************************
 * Name:          main.cpp
 * Purpose:       Implements simple wxWidgets application with GUI
 *                created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:       wxWidgets license (www.wxwidgets.org)
 *
 * Notes:         Note that all GUI creation code is implemented in
 *                gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"
#include "util.h"
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

const int WinningScore = 3;

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
    srand(time(NULL));
    
    SetTopWindow(new MainFrame(NULL, false));
    GetTopWindow()->Show();

    // true = enter the main loop
    return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow* parent, bool showLog)
    : MainFrameBase(parent)
{
    _racquetMaxSpeed = 3;
    _racquetHeight = this->_racquetPlayer->GetSize().GetHeight();
    
    this->Bind(wxEVT_CHAR_HOOK, &MainFrame::HnadleOnKeyDown, this);
    
    if (showLog)
    {
        _log = new wxLogWindow(this, "Log");
        wxLog::SetActiveTarget(_log);
    }
    else
        _log = 0;
}

MainFrame::~MainFrame()
{
    delete _log;
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
    Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
    Destroy();
}
void MainFrame::OnNewGameClick(wxCommandEvent& event)
{
    if (_gameRunning)
        return;
    
    _statusBar->PopStatusText();
    ClearScore();
    InitRound();
    
    _gameRunning = true;
}

void MainFrame::OnTimerTick(wxTimerEvent& event)
{
    wxPoint bgPositionOnScreen = _pongBackground->GetScreenPosition();
    wxSize bgSize = _pongBackground->GetSize();
    
    const wxPoint pt = getMousePositionInsideArea(bgPositionOnScreen, bgSize);
    
    wxPoint newBallPosition = MoveBall();
    
    if (CheckForWinner())
    {
        StopGame();
    }
    
    MoveRacquetTowardCoordinate(_racquetPlayer, pt.y, bgSize);
    MoveRacquetTowardCoordinate(_racquetPlayer, newBallPosition.y, bgSize);
}

void MainFrame::MoveRacquetTowardCoordinate(wxPanel* racquet, int desiredYcoordinate,
                                           const wxSize& gameboardSize)
{
    wxSize racquetSize = racquet->GetSize();
    wxPoint racquetPosition = racquet->GetPosition();
    
    int racquetHeight = racquetSize.GetHeight();
    
    racquetPosition.y += (racquetHeight / 2);
    int difference = desiredYcoordinate - racquetPosition.y;
    int direction = signum(difference);
    
    int newPosition = racquetPosition.y + (direction * min(abs(difference), _racquetMaxSpeed));
    
    if (newPosition < 0)
    {
        newPosition = 0;
    }
        
    int gameboardHeight = gameboardSize.GetHeight();
    if (newPosition > gameboardHeight)
    {
        newPosition = gameboardHeight;
    }
    
    racquetPosition.y = newPosition; 
    racquetPosition.y -= (racquetHeight / 2);
    
    // fix the "no change" magic position
    if (racquetPosition.y == -1)
        racquetPosition.y = 0;
    
    racquet->SetPosition(racquetPosition);
}

wxPoint MainFrame::MoveBall()
{
    wxPoint ballPosition = _ball->GetPosition();
    
    ballPosition.x += _ballMovement[0];
    ballPosition.y += _ballMovement[1];
    
    wxSize bg_size = _pongBackground->GetSize();
    if (ballPosition.y + 10 > bg_size.GetHeight() || ballPosition.y < 0)
        _ballMovement[1] *= -1;
        
    if (ballPosition.x < 10)
    {
        if (DoesHitRacquet(_racquetPlayer, ballPosition.y))
        {
            // todo: compute if mine racquet bounce
            _ballMovement[0] *= -1;
        }
        else
        {
            AiScores();
            InitRound();
            return ballPosition;
        }
    }
    
    // +10 - ball width, -10 racquet width -> bounce from racquet
    if (ballPosition.x + 10 > bg_size.GetWidth() - 10)
    {
        if (DoesHitRacquet(_racquetAi, ballPosition.y))
        {
            // todo: compute AI racquet bounce
            _ballMovement[0] *= -1;
        }
        else
        {
            PlayerScores();
            InitRound();
            return ballPosition;
        }
    }
        
    _ball->SetPosition(ballPosition);
    
    // return position of ball center
    ballPosition.x += 5;
    ballPosition.y += 5;
    return ballPosition;
}

bool MainFrame::DoesHitRacquet(wxPanel* racquet, int yCoord)
{
    wxPoint racquetPos = racquet->GetPosition();
    return yCoord > racquetPos.y && yCoord < racquetPos.y + _racquetHeight;
}

void MainFrame::AiScores()
{
    _score[1]++;
    _scoreAi->SetLabel(wxString::Format(wxT("%i"), _score[1]));
}

void MainFrame::StartRound()
{
    this->_gameTimer.Start(10);
}

void MainFrame::InitRound()
{
    this->_gameTimer.Stop();
    
    while (this->_ballMovement[0] == 0)
        this->_ballMovement[0] = rand() % 6 - 3;
    
    while (this->_ballMovement[1] == 0)
        this->_ballMovement[1] = rand() % 6 - 3;
    
    this->_ball->Show();
    this->_ball->CenterOnParent();
    this->_racquetPlayer->CenterOnParent();
    this->_racquetAi->CenterOnParent();
    
    this->_statusBar->PushStatusText("Game ready. Press SPACE to start.");
    this->_waitForSpace = true;
}

void MainFrame::PlayerScores()
{
    _score[0]++;
    _scorePlayer->SetLabel(wxString::Format(wxT("%i"), _score[0]));
}

bool MainFrame::CheckForWinner()
{
    if (_score[0] >= WinningScore)
    {
        _statusBar->PushStatusText("Player wins the game! Start new game to play again.");
        return true;
    }
    
    if (_score[1] >= WinningScore)
    {
        _statusBar->PushStatusText("AI wins the game! Start new game to play again.");
        return true;
    }
    
    return false;
}

void MainFrame::HnadleOnKeyDown(wxKeyEvent& event)
{
    if (_waitForSpace && event.GetKeyCode() == WXK_SPACE)
    {
        _waitForSpace = false;
        _statusBar->PopStatusText();
        StartRound();
        
        return;
    }
    
    event.Skip();
}

void MainFrame::StopGame()
{
    _gameRunning = false;
    _gameTimer.Stop();
}

void MainFrame::ClearScore()
{
    _score[0] = 0;
    _scorePlayer->SetLabel(wxString::Format(wxT("%i"), _score[0]));
    _score[1] = 0;
    _scoreAi->SetLabel(wxString::Format(wxT("%i"), _score[1]));
}
