/*********************************************************************
 * Name:          main.h
 * Purpose:       Declares simple wxWidgets application with GUI
 *                 created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:       wxWidgets license (www.wxwidgets.org)
 *
 * Notes:        Note that all GUI creation code is declared in
 *                 gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
public:
    virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase
{
private:
    bool _gameRunning;
    bool _gamePaused;
    bool _waitForSpace;
    int _racquetMaxSpeed;
    int _racquetHeight;
    int _ballMovement[2];
    int _score[2]; // 0 - player, 1 - AI
    wxLog* _log;
    
public:
    MainFrame(wxWindow* parent, bool showLog);
    virtual ~MainFrame();

protected:
    // protected event handlers
    virtual void OnCloseFrame(wxCloseEvent& event);
    virtual void OnExitClick(wxCommandEvent& event);
    virtual void OnNewGameClick(wxCommandEvent& event);
    virtual void OnTimerTick(wxTimerEvent& event);
    void HnadleOnKeyDown(wxKeyEvent& event);

private:
    void StartRound();
    void InitRound();
    void StopGame();
    void PlayerScores();
    void AiScores();
    void ClearScore();
    bool CheckForWinner();

    void MoveRacquetTowardCoordinate(wxPanel* racquet,
            int desiredYcoordinate, const wxSize& gameboardSize);
    wxPoint MoveBall();
    bool DoesHitRacquet(wxPanel* racquet, int yCoord);
    void BounceBallOnRacquet(wxPanel* racquet, int ballCenterYCoord, int xDirection);
    void SetBallMovement(int x, int y);
};

#endif //__main__
